#
# Copyright (C) 2017-2020 Alibaba Group Holding Limited
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-y += sys_clk.o
obj-y += ddr.o
else
obj-y += light.o
obj-y += board.o
endif
