# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2015 Samsung Electronics
# Przemyslaw Marczak <p.marczak@samsung.com>
#

obj-y += rambus_trng.o
obj-y += eip76_fsm.o
obj-y += eip76_fsm_stub.o
obj-y += eip76_ic.o
obj-y += eip76_init.o
obj-y += eip76_nopp.o
obj-y += eip76_random.o
obj-y += eip76_sp80090.o
obj-y += eip76_test.o
obj-y += device_rw.o