# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_VIDEO_VS_DPU) += vs_dpu.o
obj-$(CONFIG_VIDEO_DW_DSI_LIGHT) += dw_dsi_light.o
obj-$(CONFIG_VIDEO_DW_DSI_HOST) += dw_dsi_host.o
obj-$(CONFIG_VIDEO_DW_DPHY) += phy-dw-dphy.o
