//------------------------------------------------------------
// DONOT MODIFY THIS FILE
// generated by JISHENGJU automatically
//------------------------------------------------------------

#ifndef DDR_SYSREG_REG_OFFSET_DEFINE_H
#define DDR_SYSREG_REG_OFFSET_DEFINE_H

#define DDR_CFG0        0x0
#define DDR_CFG1        0x4
#define DDR_PLL_CFG0    0x8
#define DDR_PLL_CFG1    0xc
#define DDR_PLL_CFG2    0x10
#define DDR_PLL_CFG3    0x14
#define DDR_PLL_STS     0x18
#define DDR_STS0        0x1c
#define DDR_PLL_MON_STS 0x20
#define DDR_PLL_MON_CFG 0x24
#define MRR_STS_CH0     0x2c
#define MRR_STS_CH1     0x30
#define DDR_STS1        0x34
#define DDR_STS2        0x38
#define DFI0_INFO       0x3c
#define DDR_SRAM_CFG    0x40
#define DFI1_INFO       0x44
#define BPAC_CFG0       0x48
#define BPAC_CFG1       0x4c
#define BPAC_STS        0x50
#define BPDA_CFG0       0x54
#define BPDA_CFG1       0x58
#define BPDA_CFG2       0x5c
#define BPDA_CFG3       0x60
#define BPDA_STS0       0x64
#define BPDA_STS1       0x68
#define BPMA_CFG        0x6c
#define BPAC_DCH_CFG0   0x70
#define BPAC_DCH_CFG1   0x74
#define BPAC_DCH_STS    0x78
#define BPDA_DCH_CFG0   0x7c
#define BPDA_DCH_CFG1   0x80
#define BPDA_DCH_CFG2   0x84
#define BPDA_DCH_CFG3   0x88
#define BPDA_DCH_STS0   0x8c
#define BPDA_DCH_STS1   0x90
#define BPMA_DCH_CFG    0x94

#define DDR_CFG0_DFLT_VAL         0x0
#define DDR_CFG1_DFLT_VAL         0xa011f
#define DDR_PLL_CFG0_DFLT_VAL     0x1408501
#define DDR_PLL_CFG1_DFLT_VAL     0x3000000
#define DDR_PLL_CFG2_DFLT_VAL     0x2000000
#define DDR_PLL_CFG3_DFLT_VAL     0x7fff400
#define DDR_PLL_STS_DFLT_VAL      0x0
#define DDR_STS0_DFLT_VAL         0x0
#define DDR_PLL_MON_STS_DFLT_VAL  0x0
#define DDR_PLL_MON_CFG_DFLT_VAL  0x0
#define MRR_STS_CH0_DFLT_VAL      0x0
#define MRR_STS_CH1_DFLT_VAL      0x0
#define DDR_STS1_DFLT_VAL         0x0
#define DDR_STS2_DFLT_VAL         0x0
#define DFI0_INFO_DFLT_VAL        0x0
#define DDR_SRAM_CFG_DFLT_VAL     0x0
#define DFI1_INFO_DFLT_VAL        0x0
#define BPAC_CFG0_DFLT_VAL        0x0
#define BPAC_CFG1_DFLT_VAL        0x0
#define BPAC_STS_DFLT_VAL         0x0
#define BPDA_CFG0_DFLT_VAL        0x0
#define BPDA_CFG1_DFLT_VAL        0x0
#define BPDA_CFG2_DFLT_VAL        0x0
#define BPDA_CFG3_DFLT_VAL        0x0
#define BPDA_STS0_DFLT_VAL        0x0
#define BPDA_STS1_DFLT_VAL        0x0
#define BPMA_CFG_DFLT_VAL         0x0
#define BPAC_DCH_CFG0_DFLT_VAL    0x0
#define BPAC_DCH_CFG1_DFLT_VAL    0x0
#define BPAC_DCH_STS_DFLT_VAL     0x0
#define BPDA_DCH_CFG0_DFLT_VAL    0x0
#define BPDA_DCH_CFG1_DFLT_VAL    0x0
#define BPDA_DCH_CFG2_DFLT_VAL    0x0
#define BPDA_DCH_CFG3_DFLT_VAL    0x0
#define BPDA_DCH_STS0_DFLT_VAL    0x0
#define BPDA_DCH_STS1_DFLT_VAL    0x0
#define BPMA_DCH_CFG_DFLT_VAL     0x0


#endif

