#
# Copyright (C) 2017-2020 Alibaba Group Holding Limited
#
# SPDX-License-Identifier: GPL-2.0+
#

extra-y     += start.o

obj-y       += cpu.o
obj-y       += entry.o
obj-y       += exception.o
obj-y       += interrupt.o
obj-y       += crt0.o
obj-y       += timer.o
obj-y       += cache.o
