#
# Copyright (C) 2019 C-SKY MicroSystems Co.,Ltd.
#
# SPDX-License-Identifier: GPL-2.0+
#

obj-y := ice_c810_fpga.o
obj-y += gpio/gpio.o
obj-y += om/om.o

obj-$(CONFIG_SPL_BUILD) += spl/ddr.o
obj-$(CONFIG_SPL_BUILD) += spl/spl.o
